name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck
    - name: Run check on source code
      run: shellcheck --severity warning ./link.sh
